name: validate
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openpolicyagent/conftest:v0.37.0
      volumes:
        - ${{github.workspace}}:/project
    steps:
      - uses: actions/checkout@v3     
      - name: conftest
        run: |
          conftest --version
          conftest test ./serverless
